import "@/styles/globals.css";
import { Roboto, Castoro, JetBrains_Mono } from "next/font/google";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

const sansFont = Roboto({
  weight: ['300', '400', '500', '700'],
  subsets: ['latin'],
  variable: '--font-sans'
})

const displayFont = Castoro({
  weight: ['400'],
  subsets: ["latin", 'latin-ext'],
  variable: '--font-display'
})

const monoFont = JetBrains_Mono({
  weight: "400",
  subsets: ["latin"],
  variable: '--font-mono'
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/ico_ub_escut-150x150.png" sizes="32x32" />
        <link rel="icon" href="/ico_ub_escut-300x300.png" sizes="192x192" />
        <link rel="apple-touch-icon" href="/ico_ub_escut-300x300.png" />
        <meta name="msapplication-TileImage" content="/ico_ub_escut-300x300.png" />
      </head>
      <body>
        <main className={`${sansFont.variable} ${displayFont.variable} ${monoFont.variable} font-sans font-light min-h-screen`}>
          {children}
        </main>
      </body>
    </html>
  )
}
